- name: init webserver
  hosts: vms
  become: yes
  vars_files:
    - vars.yaml
  tasks:
    - name: Include vars
      include_vars: vars.yaml

    - name: Install packages
      yum:
        update_cache: yes
        name:
          - httpd
          - wget
          - awscli
          - php
          - mariadb
        state: present
    - name: install php
      command: "{{ item }}"
      with_items:
        - yum -y update
        - yum -y upgrade
        - yum install -y php
        - amazon-linux-extras install -y lamp-mariadb10.2-php7.2
        - sed -i '/LoadModule foo_module modules\/mod_foo.so/a LoadModule php7_module modules\/libphp7.so' /etc/httpd/conf/httpd.conf
        - sed -i '2s/index.html/index.html index.php/' /etc/httpd/conf/httpd.conf
        - sed -i '/AddType application\/x-gzip .gz .tgz/a AddType application\/x-httpd-php .php' /etc/httpd/conf/httpd.conf
        - sed -i '/AddType application\/x-httpd-php .php/a AddType application\/x-httpd-php-source .phps' /etc/httpd/conf/httpd.conf
        - sed -i 's/DirectoryIndex index.html/DirectoryIndex index.php/g' /etc/httpd/conf/httpd.conf
    - name: pull webserver files
      command: aws s3 sync s3://zw-aws-webserver-v2 /var/www/html/
    - name: Install CWA
      shell: "{{ item }}"
      with_items:
        - yum install -y amazon-efs-utils
        - wget https://s3.amazonaws.com/amazoncloudwatch-agent/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm
        - rpm -U ./amazon-cloudwatch-agent.rpm
        - mkdir -p /usr/share/collectd/ && touch /usr/share/collectd/types.db
        - /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c ssm:AmazonCloudWatch-linux -s

      
        

