- name: init webserver
  hosts: vms
  become: yes
  vars_files:
    - vars.yaml
  tasks:
    - name: Include vars
      include_vars: vars.yaml

    - name: Install packages
      yum:
        name:
          - httpd
          - wget
        state: present

    - name: install php
      command: "{{ item }}"
      with_items:
        - yum -y update
        - yum -y upgrade
        - yum install -y mariadb-server php
        - amazon-linux-extras install -y lamp-mariadb10.2-php7.2
        - sed -i '/LoadModule foo_module modules\/mod_foo.so/a LoadModule php7_module modules\/libphp7.so' /etc/httpd/conf/httpd.conf
        - sed -i '2s/index.html/index.html index.php/' /etc/httpd/conf/httpd.conf
        - sed -i '/AddType application\/x-gzip .gz .tgz/a AddType application\/x-httpd-php .php\nAddType   application\/x-httpd-php-source .phps' /etc/httpd/conf/httpd.conf
        - sed -i 's/DirectoryIndex index.html/DirectoryIndex index.php/g' /etc/httpd/conf/httpd.conf




    - name: start up httpd
      service: 
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items: 
        - httpd
        - mariadb

    - name: db setup script
      shell: "{{ item }}" 
      with_items:
        - mysqladmin -u root password "{{ (lookup('amazon.aws.aws_secret', aws_secret_location) | from_json)['db_root_pass'] }}"
        - echo "CREATE DATABASE {{ app_db_name }};" >> /tmp/db.setup
        - echo "CREATE USER '{{ app_db_user }}'@'localhost' IDENTIFIED BY '{{ (lookup('amazon.aws.aws_secret', aws_secret_location) | from_json)['db_user_pass'] }}';" >> /tmp/db.setup
        - echo "USE {{ app_db_name }};" >> /tmp/db.setup
        - echo "CREATE TABLE {{ app_user_table_name }} (" >> /tmp/db.setup
        - echo "    id INT AUTO_INCREMENT PRIMARY KEY," >> /tmp/db.setup
        - echo "    username VARCHAR(255) NOT NULL UNIQUE," >> /tmp/db.setup 
        - echo "    password VARCHAR(255) NOT NULL" >> /tmp/db.setup
        - echo ");" >> /tmp/db.setup
        - echo "CREATE TABLE {{ app_app_table_name }} (" >> /tmp/db.setup
        - echo "    id INT AUTO_INCREMENT PRIMARY KEY," >> /tmp/db.setup
        - echo "    user_id INT NOT NULL," >> /tmp/db.setup
        - echo "    fortune TEXT NOT NULL" >> /tmp/db.setup
        - echo "    FOREIGN KEY (user_id) REFERENCES {{ app_user_table_name }}(id)"
        - echo ");" >> /tmp/db.setup
        - echo "GRANT ALL ON {{ app_app_table_name }}.* TO '{{ app_db_user }}'@'localhost';" >> /tmp/db.setup
        - echo "GRANT ALL ON {{ app_user_table_name }}.* TO '{{ app_db_user }}'@'localhost';" >> /tmp/db.setup
        - echo "FLUSH PRIVILEGES;" >> /tmp/db.setup
        - mysql -u root --password="{{ (lookup('amazon.aws.aws_secret', aws_secret_location) | from_json)['db_root_pass'] }}" < /tmp/db.setup
      #args:
      #  creates: /tmp/db.setup
    
    - name: pull webserver files
      command: aws s3 sync s3://zw-aws-webserver-v2 /var/www/html/
    - name: permissions fix
      copy:
        dest: "/tmp/php.setup"
        content: |
          #!/bin/bash -xe
          for file in /var/www/html/*.php; do
            sed -i "s/<DB_HOST>/localhost/g" "$file"
            sed -i "s/<DB_USERNAME>/{{ app_db_user }}/g" "$file"
            sed -i "s/<DB_PASSWORD>/{{ (lookup('amazon.aws.aws_secret', aws_secret_location) | from_json)['db_user_pass'] }}/g" "$file"
            sed -i "s/<UsersTableName>/{{ app_user_table_name }}/g" "$file"
            sed -i "s/<AppTableName>/{{ app_app_table_name }}/g" "$file"
            sed -i "s/<DB_NAME>/{{ app_db_name }}/g" "$file"
          done
          chown -R ec2-user:apache /var/www
          chmod 2775 /var/www
          find /var/www -type d -exec chmod 2775 {} \;
          find /var/www -type f -exec chmod 0664 {} \;
        mode: 000500
        owner: root
        group: root
    - name: Fill placeholders with actual values in php files
      command: /tmp/php.setup
    - name: Clean up .setup files 
      shell: rm /tmp/*\.setup
      
        

